// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8KhSE9bCEwaXinVOqMRHebzvgMdvMY1k',
    appId: '1:297939322581:web:6daa971f04a8411e36c45c',
    messagingSenderId: '297939322581',
    projectId: 'your-recipes-9d8b6',
    authDomain: 'your-recipes-9d8b6.firebaseapp.com',
    storageBucket: 'your-recipes-9d8b6.appspot.com',
    measurementId: 'G-8WVTV4E9BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI5csdKTAAsK9MKQQI-CRnF1jeqDzSjsc',
    appId: '1:297939322581:android:ba8cdba85a97705636c45c',
    messagingSenderId: '297939322581',
    projectId: 'your-recipes-9d8b6',
    storageBucket: 'your-recipes-9d8b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-AKZYypABK2yknENtsSh9v7m54mX80lk',
    appId: '1:297939322581:ios:97fca16385f84a0c36c45c',
    messagingSenderId: '297939322581',
    projectId: 'your-recipes-9d8b6',
    storageBucket: 'your-recipes-9d8b6.appspot.com',
    iosBundleId: 'com.example.yourRecipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-AKZYypABK2yknENtsSh9v7m54mX80lk',
    appId: '1:297939322581:ios:af9d42d81ac8ebe336c45c',
    messagingSenderId: '297939322581',
    projectId: 'your-recipes-9d8b6',
    storageBucket: 'your-recipes-9d8b6.appspot.com',
    iosBundleId: 'com.example.yourRecipes.RunnerTests',
  );
}
