import 'dart:math';

abstract class IngredientHelper {
  static List<String> ingredientsExemples = [
    "3 xícaras e 3/4 de farinha de trigo",
    "1/2 colher de chá de sal",
    "1 xícara de açúcar",
    "2 colheres de sopa de manteiga",
    "1/4 xícara de leite",
    "1/2 colher de chá de fermento em pó",
    "1/3 xícara de óleo",
    "2 ovos",
    "1 xícara de água",
    "1 colher de sopa de essência de baunilha",
    "1/4 colher de chá de canela em pó",
    "200 gramas de chocolate amargo",
    "1/2 xícara de cacau em pó",
    "1/3 xícara de mel",
    "1/2 colher de chá de bicarbonato de sódio",
    "1/4 xícara de creme de leite",
    "2 xícaras de aveia",
    "1/3 xícara de nozes picadas",
    "1 colher de chá de raspas de limão",
    "1/4 xícara de suco de laranja",
    "1 xícara de arroz",
    "1/2 xícara de ervilhas",
    "200 gramas de queijo ralado",
    "100 gramas de presunto picado",
    "1/4 xícara de azeite de oliva",
    "1 colher de sopa de alho picado",
    "1 colher de chá de pimenta do reino",
    "1/2 colher de chá de orégano",
    "1/3 xícara de molho de tomate",
    "1/4 xícara de vinho branco",
    "1 folha de louro",
    "3 xícaras de caldo de galinha",
    "2 batatas médias cortadas em cubos",
    "1 cebola picada",
    "1/2 xícara de cenoura ralada",
    "200 gramas de camarão limpo",
    "1/4 xícara de pimentão vermelho picado",
    "1 colher de sopa de coentro picado",
    "1/2 xícara de leite de coco",
    "1 colher de chá de curry em pó",
    "1/2 xícara de creme de leite fresco",
    "1 colher de chá de noz-moscada",
    "1/4 xícara de parmesão ralado",
    "1/2 xícara de espinafre picado",
    "1/3 xícara de ricota",
    "1/4 xícara de uvas passas",
    "2 colheres de sopa de açúcar mascavo",
    "1/2 colher de chá de gengibre ralado",
    "1/4 xícara de maionese",
    "1 colher de chá de mostarda",
    "200 gramas de peito de frango desfiado",
    "1/3 xícara de ervilhas frescas",
    "1/2 xícara de milho verde",
    "1 colher de sopa de suco de limão",
    "1/2 colher de chá de páprica doce",
    "1 colher de sopa de azeite trufado",
    "1/4 xícara de vinagre balsâmico",
  ];

  static String getRandomIngredient() {
    final random = Random();
    return ingredientsExemples[random.nextInt(ingredientsExemples.length)];
  }
}
